project:
  type: website

website:
  title: "Ren Jie's IS415 Journal"
  search:
    location: navbar
    type: textbox
  reader-mode: true
  navbar:
    search: true
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: Hands-On Exercise
        menu: 
          - href: exercises/hoex1.qmd
            text: Hands-On Exercise 1
          - href: exercises/hoex2.qmd
            text: Hands-On Exercise 2
          - href: exercises/hoex3.qmd
            text: Hands-On Exercise 3
          - href: exercises/icex04.qmd
            text: Hands-On Exercise 4
          - href: exercises/hoex5.qmd
            text: Hands-On Exercise 5
          - href: exercises/hoex8.qmd
            text: Hands-On Exercise 8
      - text: In-Class Exercise
        menu: 
          - href: exercises/icex02.qmd
            text: In-Class Exercise 2
          - href: exercises/icex03.qmd
            text: In-Class Exercise 3
          - href: exercises/icex04.qmd
            text: In-Class Exercise 4
          - href: exercises/icex05.qmd
            text: In-Class Exercise 5
          - href: exercises/icex06.qmd
            text: In-Class Exercise 6
          - href: exercises/icex07.qmd
            text: In-Class Exercise 7
          - href: exercises/icex08.qmd
            text: In-Class Exercise 8
          - href: exercises/icex10.qmd
            text: In-Class Exercise 10
          - href: exercises/icex10.qmd
            text: In-Class Exercise 11
      - text: Take-home Exercise
        menu: 
          - href: exercises/thex01.qmd
            text: Take-home Exercise 1
          - href: exercises/thex02.qmd
            text: Take-home Exercise 2
          - href: exercises/thex03.qmd
            text: Take-home Exercise 3
      - text: Project
        menu: 
          - href: https://spatialbros.netlify.app/
            text: SpatialBros (Project)

      - icon: github
        href: https://github.com/renjie-teo
      - icon: linkedin
        href: https://www.linkedin.com/in/renjieteo/
      - icon: journal-album
        href: https://www.renjieteo.com
        
  page-footer:
    background: dark
    left: "Ren Jie's IS415 Geospatial Journal" 
    right: 
      - icon: github
        href: https://github.com/renj1ete0
      - icon: linkedin
        href: https://www.linkedin.com/in/renjieteo/
      - icon: journal-album
        href: https://www.renjieteo.com

format:
  html:
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    fontsize: 0.98em
    linestretch: 1.7
    css: styles.css
    toc: true

editor: visual

