project:
  type: website

website:
  title: "Ren Jie's IS415 Journal"
  search:
    location: navbar
    type: textbox
  reader-mode: true
  navbar:
    search: true
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: index.qmd#category=Hands-on Exercise
        text: Hands-On Exercise
      - icon: github
        href: https://github.com/renjie-teo
      - icon: linkedin
        href: https://www.linkedin.com/in/renjieteo/
        
  page-footer:
    background: light
    left: "Ren Jie's IS415 Journal" 
    right: 
      - icon: github
        href: https://github.com/renjie-teo
      - icon: linkedin
        href: https://www.linkedin.com/in/renjieteo/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

