<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Teo Ren Jie">
<meta name="dcterms.date" content="2023-01-15">
<meta name="description" content="In this exercise, I learn how to handle, perform geoprocessing and EDA using sf, tidyverse, ggplot2 and other packages.">

<title>Ren Jie’s IS415 Journal - Hands-on Exercise 1: Geospatial Data Handling and Wrangling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Ren Jie’s IS415 Journal</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-On Exercise</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../exercises/hoex1.html">
 <span class="dropdown-text">Hands-On Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/hoex2.html">
 <span class="dropdown-text">Hands-On Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/hoex3.html">
 <span class="dropdown-text">Hands-On Exercise 3</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercise</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../exercises/icex02.html">
 <span class="dropdown-text">In-Class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/icex03.html">
 <span class="dropdown-text">In-Class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/icex04.html">
 <span class="dropdown-text">In-Class Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../exercises/thex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/renjie-teo"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/renjieteo/"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-reader-toggle nav-link" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Hands-on Exercise 1: Geospatial Data Handling and Wrangling</h1>
                  <div>
        <div class="description">
          In this exercise, I learn how to handle, perform geoprocessing and EDA using sf, tidyverse, ggplot2 and other packages.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Hands-on Exercise</div>
                <div class="quarto-category">tidyverse</div>
                <div class="quarto-category">sf</div>
                <div class="quarto-category">ggplot2</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Teo Ren Jie </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 15, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">1. Getting Started</a>
  <ul class="collapse">
  <li><a href="#installing-and-loading-packages" id="toc-installing-and-loading-packages" class="nav-link" data-scroll-target="#installing-and-loading-packages">1.1 Installing and Loading Packages</a></li>
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition">1.2 Data Acquisition</a></li>
  <li><a href="#importing-geospatial-shapefile-datasets" id="toc-importing-geospatial-shapefile-datasets" class="nav-link" data-scroll-target="#importing-geospatial-shapefile-datasets">1.3 Importing Geospatial Shapefile Datasets</a>
  <ul class="collapse">
  <li><a href="#importing-master-plan-2014-subzone-boundary-web" id="toc-importing-master-plan-2014-subzone-boundary-web" class="nav-link" data-scroll-target="#importing-master-plan-2014-subzone-boundary-web">1.3.1 Importing Master Plan 2014 Subzone Boundary (Web)</a></li>
  <li><a href="#importing-cycling-path" id="toc-importing-cycling-path" class="nav-link" data-scroll-target="#importing-cycling-path">1.3.2 Importing Cycling Path</a></li>
  </ul></li>
  <li><a href="#importing-geospatial-gis-datasets-in-kml-format" id="toc-importing-geospatial-gis-datasets-in-kml-format" class="nav-link" data-scroll-target="#importing-geospatial-gis-datasets-in-kml-format">1.4 Importing Geospatial GIS Datasets in kml format</a>
  <ul class="collapse">
  <li><a href="#importing-pre-schools-location" id="toc-importing-pre-schools-location" class="nav-link" data-scroll-target="#importing-pre-schools-location">1.4.1 Importing Pre-Schools Location</a></li>
  </ul></li>
  <li><a href="#additional-notes" id="toc-additional-notes" class="nav-link" data-scroll-target="#additional-notes">1.5 Additional Notes</a></li>
  </ul></li>
  <li><a href="#checking-content-of-a-simple-feature-data-frame" id="toc-checking-content-of-a-simple-feature-data-frame" class="nav-link" data-scroll-target="#checking-content-of-a-simple-feature-data-frame">2. Checking Content of a Simple Feature Data Frame</a>
  <ul class="collapse">
  <li><a href="#st_geometry" id="toc-st_geometry" class="nav-link" data-scroll-target="#st_geometry">2.1 st_geometry()</a></li>
  <li><a href="#glimpse" id="toc-glimpse" class="nav-link" data-scroll-target="#glimpse">2.2 glimpse()</a></li>
  <li><a href="#head" id="toc-head" class="nav-link" data-scroll-target="#head">2.3 head()</a></li>
  </ul></li>
  <li><a href="#plotting-geospatial-data" id="toc-plotting-geospatial-data" class="nav-link" data-scroll-target="#plotting-geospatial-data">3. Plotting Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#multi-plot-attributes" id="toc-multi-plot-attributes" class="nav-link" data-scroll-target="#multi-plot-attributes">3.1 Multi-plot Attributes</a></li>
  <li><a href="#geometry-plot" id="toc-geometry-plot" class="nav-link" data-scroll-target="#geometry-plot">3.2 Geometry Plot</a></li>
  <li><a href="#specific-attributes" id="toc-specific-attributes" class="nav-link" data-scroll-target="#specific-attributes">3.3 Specific Attributes</a></li>
  </ul></li>
  <li><a href="#working-with-projection" id="toc-working-with-projection" class="nav-link" data-scroll-target="#working-with-projection">4. Working with Projection</a>
  <ul class="collapse">
  <li><a href="#assigning-epsg-code-to-a-simple-feature-data-frame" id="toc-assigning-epsg-code-to-a-simple-feature-data-frame" class="nav-link" data-scroll-target="#assigning-epsg-code-to-a-simple-feature-data-frame">4.1 Assigning EPSG Code to a Simple Feature Data Frame</a>
  <ul class="collapse">
  <li><a href="#checking-the-coordinate-system-of-the-data-frame" id="toc-checking-the-coordinate-system-of-the-data-frame" class="nav-link" data-scroll-target="#checking-the-coordinate-system-of-the-data-frame">4.1.1 Checking the Coordinate System of the Data Frame</a></li>
  <li><a href="#transforming-from-wgs84-to-svy21" id="toc-transforming-from-wgs84-to-svy21" class="nav-link" data-scroll-target="#transforming-from-wgs84-to-svy21">4.1.2 Transforming from wgs84 to svy21</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#importing-and-converting-aspatial-data" id="toc-importing-and-converting-aspatial-data" class="nav-link" data-scroll-target="#importing-and-converting-aspatial-data">5. Importing and Converting Aspatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-aspatial-data" id="toc-importing-aspatial-data" class="nav-link" data-scroll-target="#importing-aspatial-data">5.1 Importing Aspatial Data</a></li>
  <li><a href="#creating-a-simple-feature-data-frame-from-an-aspatial-data-frame" id="toc-creating-a-simple-feature-data-frame-from-an-aspatial-data-frame" class="nav-link" data-scroll-target="#creating-a-simple-feature-data-frame-from-an-aspatial-data-frame">5.2 Creating a Simple Feature Data Frame from an Aspatial Data Frame</a></li>
  <li><a href="#examining-simple-feature-data-frame" id="toc-examining-simple-feature-data-frame" class="nav-link" data-scroll-target="#examining-simple-feature-data-frame">5.3 Examining Simple Feature Data Frame</a></li>
  </ul></li>
  <li><a href="#geoprocessing-with-sf-package" id="toc-geoprocessing-with-sf-package" class="nav-link" data-scroll-target="#geoprocessing-with-sf-package">6. Geoprocessing with sf Package</a>
  <ul class="collapse">
  <li><a href="#buffering" id="toc-buffering" class="nav-link" data-scroll-target="#buffering">6.1 Buffering</a></li>
  <li><a href="#point-in-polygon-count" id="toc-point-in-polygon-count" class="nav-link" data-scroll-target="#point-in-polygon-count">6.2 Point-in-polygon Count</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">7. Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#investigating-pre-school-density" id="toc-investigating-pre-school-density" class="nav-link" data-scroll-target="#investigating-pre-school-density">7.1 Investigating Pre School Density</a>
  <ul class="collapse">
  <li><a href="#histogram-hist-of-mpsz3414presch-density" id="toc-histogram-hist-of-mpsz3414presch-density" class="nav-link" data-scroll-target="#histogram-hist-of-mpsz3414presch-density">7.1.1 Histogram (hist) of mpsz3414$<code>PreSch Density</code></a></li>
  <li><a href="#histogram-ggplot2-of-mpsz3414presch-density" id="toc-histogram-ggplot2-of-mpsz3414presch-density" class="nav-link" data-scroll-target="#histogram-ggplot2-of-mpsz3414presch-density">7.1.2 Histogram (ggplot2) of mpsz3414$<code>PreSch Density</code></a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="getting-started" class="level1">
<h1>1. Getting Started</h1>
<hr>
<section id="installing-and-loading-packages" class="level2">
<h2 class="anchored" data-anchor-id="installing-and-loading-packages">1.1 Installing and Loading Packages</h2>
<p>Firstly, the code below will check if <strong>pacman</strong> has been installed. If it has not been installed, R will download and install it, before activating it for use during this session.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-1_42371cba162a79ccb710276a183ac6b4">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">'pacman'</span>, <span class="at">character.only =</span> T)){</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'pacman'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: pacman</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'pacman'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, pacman assists us by helping us load R packages that we require, <code>sf</code> and <code>tidyverse</code>.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-2_93eb4ac6c302d4a03b3d0fb04f069965">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-acquisition" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition">1.2 Data Acquisition</h2>
<p>For the purpose of this exercise, the following public datasets are used:</p>
<table class="table">
<thead>
<tr class="header">
<th>Dataset Name</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Master Plan 2014 Subzone Boundary (Web) <em>(MP14_SUBZONE_WEB_PL.shp)</em></td>
<td><a href="https://data.gov.sg/dataset/master-plan-2014-subzone-boundary-web">data.gov.sg</a></td>
</tr>
<tr class="even">
<td>Pre-Schools Location <em>(preschools-location.kml)</em></td>
<td><a href="https://dataportal.asia/dataset/203030733_pre-schools-location">data.gov.sg</a></td>
</tr>
<tr class="odd">
<td>Cycling Path <em>(CyclingPathGazette.shp)</em></td>
<td><a href="https://datamall.lta.gov.sg/content/datamall/en/search_datasets.html?searchText=Cycling%20Path">LTA Datamall</a></td>
</tr>
<tr class="even">
<td>Latest version of Singapore Airbnb listing data <em>(listings.csv)</em></td>
<td><a href="http://insideairbnb.com/get-the-data/">Inside Airbnb</a></td>
</tr>
</tbody>
</table>
<p>The data has been extracted to <code>Hands-on_Ex01/data/geospatial</code>.</p>
<p>Master Plan and Cycling Path layers are provided in ES</p>
<p>RI shapefile format, Pre-Schools Location provided in kml and Airbnb listings in csv format.</p>
</section>
<section id="importing-geospatial-shapefile-datasets" class="level2">
<h2 class="anchored" data-anchor-id="importing-geospatial-shapefile-datasets">1.3 Importing Geospatial Shapefile Datasets</h2>
<p>There are two shapefile (.shp) datasets, Master Plan 2014 Subzone Boundary (Web) and Cycling Path.</p>
<section id="importing-master-plan-2014-subzone-boundary-web" class="level3">
<h3 class="anchored" data-anchor-id="importing-master-plan-2014-subzone-boundary-web">1.3.1 Importing Master Plan 2014 Subzone Boundary (Web)</h3>
<p>Firstly, we will import Master Plan 2014 Subzone Boundary (Web). In the code below, <code>dsn</code> specifies the filepath where the dataset is located and <code>layer</code> provides the filename of the dataset excluding the file extension.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-3_afaebec795797da904ed29eafaf24d85">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"Hands-on_Ex01/data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `C:\renjie-teo\IS415-GAA\exercises\Hands-on_Ex01\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
</div>
<p>From the above message, it tells us that the dataset contains <code>multipolygon</code> features, containing 323 multipolygon features and 15 fields in the <code>mpsz</code> simple feature data frame and is in the <code>svy21</code> projected coordinates system. The bounding box provides us the x and y <code>extents</code> (x min, x max, y min, y max) of the data.</p>
</section>
<section id="importing-cycling-path" class="level3">
<h3 class="anchored" data-anchor-id="importing-cycling-path">1.3.2 Importing Cycling Path</h3>
<p>Next, we will import Cycling Path.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-4_13f12637f2d3ba6d65a8c8a036889552">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>cyclingpath <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"Hands-on_Ex01/data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"CyclingPathGazette"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `CyclingPathGazette' from data source 
  `C:\renjie-teo\IS415-GAA\exercises\Hands-on_Ex01\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 2248 features and 2 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 11854.32 ymin: 28347.98 xmax: 42626.09 ymax: 48948.15
Projected CRS: SVY21</code></pre>
</div>
</div>
<p>From the above message, it tells us that the dataset contains <code>mutlilinestring</code> features, containing <strong>2248 multilinestring features</strong> and <strong>2 fields</strong> in the <code>cyclingpath</code> simple feature data frame and is in the <code>svy21</code> projected coordinates system. Similarly, the bounding box provides us the x and y <code>extents</code> (x min, x max, y min, y max) of the data.</p>
</section>
</section>
<section id="importing-geospatial-gis-datasets-in-kml-format" class="level2">
<h2 class="anchored" data-anchor-id="importing-geospatial-gis-datasets-in-kml-format">1.4 Importing Geospatial GIS Datasets in kml format</h2>
<p>There is one kml dataset, Pre-Schools Location, that we have to import.</p>
<section id="importing-pre-schools-location" class="level3">
<h3 class="anchored" data-anchor-id="importing-pre-schools-location">1.4.1 Importing Pre-Schools Location</h3>
<p>In the code below, we do not specify <code>dsn</code> and <code>layer</code>. Just the filepath and filename will suffice.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-5_c71d7f79257474982893c9c03abc6245">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>preschools <span class="ot">=</span> <span class="fu">st_read</span>(<span class="st">"Hands-on_Ex01/data/geospatial/preschools-location.kml"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `PRESCHOOLS_LOCATION' from data source 
  `C:\renjie-teo\IS415-GAA\exercises\Hands-on_Ex01\data\geospatial\preschools-location.kml' 
  using driver `KML'
Simple feature collection with 1925 features and 2 fields
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.6824 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>From the above message, it tells us that the dataset contains <code>point</code> features, containing <strong>1359 features</strong> and <strong>2 fields</strong> and is in the <code>wgs84</code> projected coordinates system. Similarly, the bounding box provides us the x and y <code>extents</code> (x min, x max, y min, y max) of the data.</p>
</section>
</section>
<section id="additional-notes" class="level2">
<h2 class="anchored" data-anchor-id="additional-notes">1.5 Additional Notes</h2>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Do recall that there are 2 different coordinate systems in use for the datasets here. Master Plan and Cycling Path utilises <code>svy21</code> and Pre-Schools utilises <code>wgs84</code>.</p>
</div>
</div>
</div>
</section>
</section>
<section id="checking-content-of-a-simple-feature-data-frame" class="level1">
<h1>2. Checking Content of a Simple Feature Data Frame</h1>
<hr>
<p>There are some methods to obtain information about a data frame quickly.</p>
<section id="st_geometry" class="level2">
<h2 class="anchored" data-anchor-id="st_geometry">2.1 st_geometry()</h2>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-6_c3a42a43ff06a632fdd1f9d3754a486b">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 323 features 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((31495.56 30140.01, 31980.96 296...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29092.28 30021.89, 29119.64 300...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29932.33 29879.12, 29947.32 298...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((27131.28 30059.73, 27088.33 297...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((26451.03 30396.46, 26440.47 303...</code></pre>
</div>
</div>
<p>st_geometry() can help us obtain summarised details about a dataset about the geometry. In the case on The information provided is the same as what we have seen while importing the datasets earlier on.</p>
</section>
<section id="glimpse" class="level2">
<h2 class="anchored" data-anchor-id="glimpse">2.2 glimpse()</h2>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-7_8e1d6bf56a51bdf61ee7536e6d181813">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 323
Columns: 16
$ OBJECTID   &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …
$ SUBZONE_NO &lt;int&gt; 1, 1, 3, 8, 3, 7, 9, 2, 13, 7, 12, 6, 1, 5, 1, 1, 3, 2, 2, …
$ SUBZONE_N  &lt;chr&gt; "MARINA SOUTH", "PEARL'S HILL", "BOAT QUAY", "HENDERSON HIL…
$ SUBZONE_C  &lt;chr&gt; "MSSZ01", "OTSZ01", "SRSZ03", "BMSZ08", "BMSZ03", "BMSZ07",…
$ CA_IND     &lt;chr&gt; "Y", "Y", "Y", "N", "N", "N", "N", "Y", "N", "N", "N", "N",…
$ PLN_AREA_N &lt;chr&gt; "MARINA SOUTH", "OUTRAM", "SINGAPORE RIVER", "BUKIT MERAH",…
$ PLN_AREA_C &lt;chr&gt; "MS", "OT", "SR", "BM", "BM", "BM", "BM", "SR", "QT", "QT",…
$ REGION_N   &lt;chr&gt; "CENTRAL REGION", "CENTRAL REGION", "CENTRAL REGION", "CENT…
$ REGION_C   &lt;chr&gt; "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR",…
$ INC_CRC    &lt;chr&gt; "5ED7EB253F99252E", "8C7149B9EB32EEFC", "C35FEFF02B13E0E5",…
$ FMEL_UPD_D &lt;date&gt; 2014-12-05, 2014-12-05, 2014-12-05, 2014-12-05, 2014-12-05…
$ X_ADDR     &lt;dbl&gt; 31595.84, 28679.06, 29654.96, 26782.83, 26201.96, 25358.82,…
$ Y_ADDR     &lt;dbl&gt; 29220.19, 29782.05, 29974.66, 29933.77, 30005.70, 29991.38,…
$ SHAPE_Leng &lt;dbl&gt; 5267.381, 3506.107, 1740.926, 3313.625, 2825.594, 4428.913,…
$ SHAPE_Area &lt;dbl&gt; 1630379.27, 559816.25, 160807.50, 595428.89, 387429.44, 103…
$ geometry   &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((31495.56 30..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>glimpse() can help us investigate what are the specific fields, its associated field data type and some sample data from the dataset to help us visualize the structure of the data.</p>
</section>
<section id="head" class="level2">
<h2 class="anchored" data-anchor-id="head">2.3 head()</h2>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-8_654b3001b414cf596040301f867ac2a1">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mpsz, <span class="at">n=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 5 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 25867.68 ymin: 28369.47 xmax: 32362.39 ymax: 30435.54
Projected CRS: SVY21
  OBJECTID SUBZONE_NO      SUBZONE_N SUBZONE_C CA_IND      PLN_AREA_N
1        1          1   MARINA SOUTH    MSSZ01      Y    MARINA SOUTH
2        2          1   PEARL'S HILL    OTSZ01      Y          OUTRAM
3        3          3      BOAT QUAY    SRSZ03      Y SINGAPORE RIVER
4        4          8 HENDERSON HILL    BMSZ08      N     BUKIT MERAH
5        5          3        REDHILL    BMSZ03      N     BUKIT MERAH
  PLN_AREA_C       REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR
1         MS CENTRAL REGION       CR 5ED7EB253F99252E 2014-12-05 31595.84
2         OT CENTRAL REGION       CR 8C7149B9EB32EEFC 2014-12-05 28679.06
3         SR CENTRAL REGION       CR C35FEFF02B13E0E5 2014-12-05 29654.96
4         BM CENTRAL REGION       CR 3775D82C5DDBEFBD 2014-12-05 26782.83
5         BM CENTRAL REGION       CR 85D9ABEF0A40678F 2014-12-05 26201.96
    Y_ADDR SHAPE_Leng SHAPE_Area                       geometry
1 29220.19   5267.381  1630379.3 MULTIPOLYGON (((31495.56 30...
2 29782.05   3506.107   559816.2 MULTIPOLYGON (((29092.28 30...
3 29974.66   1740.926   160807.5 MULTIPOLYGON (((29932.33 29...
4 29933.77   3313.625   595428.9 MULTIPOLYGON (((27131.28 30...
5 30005.70   2825.594   387429.4 MULTIPOLYGON (((26451.03 30...</code></pre>
</div>
</div>
<p>head() can also help us obtain summarised details about a dataset as with glimpse(). Using the <code>n=5</code> parameter inside function head, we are able to limit the amount of features to be shown to 5.</p>
</section>
</section>
<section id="plotting-geospatial-data" class="level1">
<h1>3. Plotting Geospatial Data</h1>
<hr>
<p>There are various methods to plot geospatial features into a graphical format, other than just looking at feature information.</p>
<section id="multi-plot-attributes" class="level2">
<h2 class="anchored" data-anchor-id="multi-plot-attributes">3.1 Multi-plot Attributes</h2>
<p>The following code will plot multiple attributes within the dataframe up to a reasonable limit.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-9_652df3f3ab12e85ff965fe9967c74c98">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: plotting the first 9 out of 15 attributes; use max.plot = 15 to plot
all</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hoex1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="geometry-plot" class="level2">
<h2 class="anchored" data-anchor-id="geometry-plot">3.2 Geometry Plot</h2>
<p>Recall st_geometry from <code>Checking Content of a Simple Data Frame</code> from earlier? st_geometry provides the geometry of the map, where we could use plot to plot just the geomtry of the data frame.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-10_2577594a7838afa7d1e20f7c03fbff4c">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(mpsz))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hoex1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="specific-attributes" class="level2">
<h2 class="anchored" data-anchor-id="specific-attributes">3.3 Specific Attributes</h2>
<p>We could also choose to plot a specific attribute of the data frame. The following code below will plot the <code>PLN_AREA_N</code> attribute.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-11_c696af4c42938dd6e0ffb04172f839c7">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz[<span class="st">"PLN_AREA_N"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hoex1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="working-with-projection" class="level1">
<h1>4. Working with Projection</h1>
<hr>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Recall that our datasets are in two different coordinate systems, <code>wgs84</code> and <code>svy21</code></p>
</div>
</div>
</div>
<p>To perform geoprocessing with two or more geospatial datasets, we need to ensure the datasets ar eprojected using a similar coordinate system.</p>
<p>Here, we will project a simple feature dataframe from one coordinate system to another.</p>
<section id="assigning-epsg-code-to-a-simple-feature-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="assigning-epsg-code-to-a-simple-feature-data-frame">4.1 Assigning EPSG Code to a Simple Feature Data Frame</h2>
<p>The coordinate system in the dataset could be wrongly assigned during the importing process or missing (missing .proj file for ESRI shapefile) when importing geospatial data into R.</p>
<section id="checking-the-coordinate-system-of-the-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="checking-the-coordinate-system-of-the-data-frame">4.1.1 Checking the Coordinate System of the Data Frame</h3>
<p>To check the coordinate system of a dataset, the <em>st_crs()</em> function of sf package could be used. Here, we check the coordinate system of <code>mpsz</code> simple feature data frame.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-12_8362f2405ba929f4b710f4092be5e1b9">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: SVY21 
  wkt:
PROJCRS["SVY21",
    BASEGEOGCRS["SVY21[WGS84]",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]</code></pre>
</div>
</div>
<p>Although the data frame has been projected in <code>SVY21</code>, if we look at the end of the output, it indicates that the EPSG is 9001 which is incorrect. The correct EPSG code for <code>SVY21</code> should be <a href="https://epsg.io/3414">3414</a>.</p>
<p>In the code chunk below, we will correct the crs to EPSG 3414.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-13_61a4f5433767cc97c341b7fa3970500c">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mpsz3414 <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(mpsz,<span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: st_crs&lt;- : replacing crs does not reproject data; use st_transform for
that</code></pre>
</div>
</div>
<p>Now, let us check the crs if it has been updated.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-14_20a6f2724f088a1ff09dfa1f5043196a">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz3414)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
<p>Now, the EPSG has been updated to 3414.</p>
</section>
<section id="transforming-from-wgs84-to-svy21" class="level3">
<h3 class="anchored" data-anchor-id="transforming-from-wgs84-to-svy21">4.1.2 Transforming from wgs84 to svy21</h3>
<p>It is important in geospatial analytics to ensure that datasets are converted to projected coordinate system from the geographic coordinate system. Geographic coordinate system is not appropriate if analysis requires distance and/or area measurements.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-15_c34d0b9788dc17d555253384d9114531">
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>In the preschools data frame, it is in the <code>wgs84</code> coordinate system.</p>
<p>Since reprojection is necessary from <code>wgs84</code> to <code>svy21</code> mathematically, <em>st_set_crs()</em>&nbsp;would not be appropriate. We will utilise <em>st_transform()</em>.</p>
<p>In the example below, we reproject the <code>preschools</code> dataframe to <code>svy21</code>&nbsp;(EPSG 3414).</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-16_c95f05b2b11cab1cce82926e64d869c7">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>preschools3414 <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(preschools, <span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s see the content of the reprojected <code>preschools3414</code> dataframe.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-17_81341458663201b6c11a0af090f07c40">
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
<p>Now, the data frame is in <code>svy21</code> coordinate system.</p>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>If the bounding box values are greater than the 0-360 decimal degree used by most geographic coordinate system, it means it is likely to be in a projected coordinate system.</p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="importing-and-converting-aspatial-data" class="level1">
<h1>5. Importing and Converting Aspatial Data</h1>
<hr>
<p>Sometimes, data do not come in geospatial data format, such as <code>listing</code> of Inside Airbnb. These are called data aspatial data, where it is not geospatial data, but contains x and y coordinates within its fields.</p>
<section id="importing-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-aspatial-data">5.1 Importing Aspatial Data</h2>
<p>Since <code>listings</code> data set is in <code>csv</code> format, we will used read_csv() of <strong>readr</strong> package to import <code>listing.csv</code> and output it to an R object called <code>listings</code>, which is a tibble data frame.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-18_dc4284836e87f4b41f93efa5de72bed7">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>listings <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Hands-on_Ex01/data/aspatial/listings.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 4161 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (6): name, host_name, neighbourhood_group, neighbourhood, room_type, l...
dbl  (11): id, host_id, latitude, longitude, price, minimum_nights, number_o...
date  (1): last_review

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Instead of using <em>glimpse()</em> as shown earlier, <em>list()</em>&nbsp;could also do the job.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-19_98e2f89a0b6a3dbfc1c1fa904065a134">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(listings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 4,161 × 18
       id name     host_id host_…¹ neigh…² neigh…³ latit…⁴ longi…⁵ room_…⁶ price
    &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;
 1  50646 Pleasan…  227796 Sujatha Centra… Bukit …    1.33    104. Privat…    80
 2  71609 Ensuite…  367042 Belinda East R… Tampin…    1.35    104. Privat…   145
 3  71896 B&amp;B  Ro…  367042 Belinda East R… Tampin…    1.35    104. Privat…    85
 4  71903 Room 2-…  367042 Belinda East R… Tampin…    1.35    104. Privat…    85
 5 275344 15 mins… 1439258 Kay     Centra… Bukit …    1.29    104. Privat…    49
 6 289234 Booking…  367042 Belinda East R… Tampin…    1.34    104. Privat…   184
 7 294281 5 mins … 1521514 Elizab… Centra… Newton     1.31    104. Privat…    79
 8 324945 Cozy Bl… 1439258 Kay     Centra… Bukit …    1.29    104. Privat…    49
 9 330089 Cozy Bl… 1439258 Kay     Centra… Bukit …    1.29    104. Privat…    55
10 330095 10 mins… 1439258 Kay     Centra… Bukit …    1.29    104. Privat…    55
# … with 4,151 more rows, 8 more variables: minimum_nights &lt;dbl&gt;,
#   number_of_reviews &lt;dbl&gt;, last_review &lt;date&gt;, reviews_per_month &lt;dbl&gt;,
#   calculated_host_listings_count &lt;dbl&gt;, availability_365 &lt;dbl&gt;,
#   number_of_reviews_ltm &lt;dbl&gt;, license &lt;chr&gt;, and abbreviated variable names
#   ¹​host_name, ²​neighbourhood_group, ³​neighbourhood, ⁴​latitude, ⁵​longitude,
#   ⁶​room_type</code></pre>
</div>
</div>
<p>Our output shows our <code>listing</code> tibble data frame consists of <strong>4161 rows</strong> and <strong>18 columns</strong>. The useful fields we would be paying attention to is the <code>latitude</code> and <code>longitude</code> columns, which are in the decimal degree format. By assumption, we assume the data is in <code>wgs84</code> Geographic Coordinate System.</p>
</section>
<section id="creating-a-simple-feature-data-frame-from-an-aspatial-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-simple-feature-data-frame-from-an-aspatial-data-frame">5.2 Creating a Simple Feature Data Frame from an Aspatial Data Frame</h2>
<p>The code below converts the <code>listings</code> tibble data fame into a simple feature data frame by using <em>st_as_sf()</em> from <strong>sf</strong> packages, which converts foreign data formats to an sf object.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-20_eb683125a83d8592c61152b763ebd1bb">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>listings_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(listings,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The arguments for</p>
<ul>
<li><p><em>listings</em> could be any other foreign data frame to be converted</p></li>
<li><p><em>coords</em> requires to provide column name of x-coordinates followed by y-coordinates. The coordinates system also needs to be provided in terms of EPSG format. EPSG:4326 is the <code>wgs84</code> Geographic Coordinate System whereas EPSG:3414 is Singapore’s <code>svy21</code> Projected Coordinate System.</p></li>
<li><p><em>%&gt;%</em> nest <em>st_transform()</em> into the <em>st_as_sf()</em>&nbsp;function to convert into <code>svy21</code> coordinates</p></li>
</ul>
</section>
<section id="examining-simple-feature-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="examining-simple-feature-data-frame">5.3 Examining Simple Feature Data Frame</h2>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-21_6a0b9a2e0f0c521a5674b472d3dc6a44">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(listings_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,161
Columns: 17
$ id                             &lt;dbl&gt; 50646, 71609, 71896, 71903, 275344, 289…
$ name                           &lt;chr&gt; "Pleasant Room along Bukit Timah", "Ens…
$ host_id                        &lt;dbl&gt; 227796, 367042, 367042, 367042, 1439258…
$ host_name                      &lt;chr&gt; "Sujatha", "Belinda", "Belinda", "Belin…
$ neighbourhood_group            &lt;chr&gt; "Central Region", "East Region", "East …
$ neighbourhood                  &lt;chr&gt; "Bukit Timah", "Tampines", "Tampines", …
$ room_type                      &lt;chr&gt; "Private room", "Private room", "Privat…
$ price                          &lt;dbl&gt; 80, 145, 85, 85, 49, 184, 79, 49, 55, 5…
$ minimum_nights                 &lt;dbl&gt; 92, 92, 92, 92, 60, 92, 92, 60, 60, 60,…
$ number_of_reviews              &lt;dbl&gt; 18, 20, 24, 47, 14, 12, 133, 17, 12, 3,…
$ last_review                    &lt;date&gt; 2014-12-26, 2020-01-17, 2019-10-13, 20…
$ reviews_per_month              &lt;dbl&gt; 0.18, 0.15, 0.18, 0.34, 0.11, 0.10, 1.0…
$ calculated_host_listings_count &lt;dbl&gt; 1, 6, 6, 6, 44, 6, 7, 44, 44, 44, 6, 7,…
$ availability_365               &lt;dbl&gt; 365, 340, 265, 365, 296, 285, 365, 181,…
$ number_of_reviews_ltm          &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 3, 2, 0, 1, 0, 0, …
$ license                        &lt;chr&gt; NA, NA, NA, NA, "S0399", NA, NA, "S0399…
$ geometry                       &lt;POINT [m]&gt; POINT (22646.02 35167.9), POINT (…</code></pre>
</div>
</div>
<p>Previously, there were <strong>18 columns</strong> in the aspatial data, only <strong>17 columns</strong> exists now. <code>Longitude</code> and <code>Latitude</code> columns were dropped and a new column has been created for <code>geometry</code>.</p>
</section>
</section>
<section id="geoprocessing-with-sf-package" class="level1">
<h1>6. Geoprocessing with sf Package</h1>
<hr>
<p>Besides providing functions to handle (import, export, projection, etc.) geospatial data, <strong>sf</strong> package can also perform geoprocessing (also known as GIS analysis functions).</p>
<section id="buffering" class="level2">
<h2 class="anchored" data-anchor-id="buffering">6.1 Buffering</h2>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Scenario:</p>
<p>The authority is planning to upgrade the existing cycling path. To do so, they need to acquire 5 metres of reserved land on both sides of the current cycling path. You are tasked to determine the extent of land needed to be acquired and their total area.</p>
</div>
</div>
</div>
<p>Firstly, we utilise <em>st_buffer()</em>&nbsp;of <strong>sf</strong> package to compute the 5-metre buffers around cycling paths.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-22_d42d0431ea94c955d4f7a2d1111ba14c">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>buffer_cycling <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(cyclingpath,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">dist =</span> <span class="dv">5</span>,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">nQuadSegs =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What <code>nQuadSegs</code> alters is the generalisation of points to create the buffer. More segments means it is less generalised and less segments means more generalised buffers.</p>
<p>Next, we calculate the area of the buffers.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-23_cd0bf2dbb532ac96300e53a0f0adafe6">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>buffer_cycling<span class="sc">$</span>AREA <span class="ot">&lt;-</span> <span class="fu">st_area</span>(buffer_cycling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can sum the area to get total land required for the buffer.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-24_5c8ba50986b07c864873860576b43628">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(buffer_cycling<span class="sc">$</span>AREA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1556978 [m^2]</code></pre>
</div>
</div>
</section>
<section id="point-in-polygon-count" class="level2">
<h2 class="anchored" data-anchor-id="point-in-polygon-count">6.2 Point-in-polygon Count</h2>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Scenario:</p>
<p>A pre-school service group wants to find the number of pre-schools in each Planning Subzone.</p>
</div>
</div>
</div>
<p>Firstly, we utilise <em>st_intersects()</em> of <strong>sf</strong> package to find which pre-schools falls under which planning subzone. Then, using lengths, we calculate the number of pre-schools within each planning subzone.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-25_19b551cffe14d79fd5b1f53e182a65d2">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(mpsz3414, preschools3414))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We could use <em>summary()</em> to viewsummary statistics of the newly derived <em>PreSch Count</em> field.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-26_890036d19f112145956267cd2926d54b">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00    3.00    5.96    9.00   58.00 </code></pre>
</div>
</div>
<p>Wow! Here, we can see that there is at least one planning subzone with 58 pre-schools, with a mean of 5.96 pre-schools in each subzone.</p>
<p>Now, let’s look at the top sub-zone with the most pre-schools.</p>
<p>The code below utilises <em>top_n</em> of <strong>dplyr</strong> package to look in the mpsz3414 dataframe, under the field PreSch Count for the top record</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-27_fbc512e0943cfec9265c35a62a7c813d">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">top_n</span>(mpsz3414, <span class="dv">1</span>, <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 39655.33 ymin: 35966 xmax: 42940.57 ymax: 38622.37
Projected CRS: SVY21 / Singapore TM
  OBJECTID SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C
1      189          2 TAMPINES EAST    TMSZ02      N   TAMPINES         TM
     REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR   Y_ADDR SHAPE_Leng
1 EAST REGION       ER 21658EAAF84F4D8D 2014-12-05 41122.55 37392.39   10180.62
  SHAPE_Area                       geometry PreSch Count
1    4339824 MULTIPOLYGON (((42196.76 38...           58</code></pre>
</div>
</div>
<p>Here, we can see that the top planning subzone with the most preschools is Tampines East.</p>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Scenario:</p>
<p>Calculate the density of pre-school by planning subzone</p>
</div>
</div>
</div>
<p>First, the formula for density is <code>density = count / area</code></p>
<p>We will first calculate the area of each subzone below:</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-28_80819f5bb67f0e69332d9dbe681d32a6">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span>Area <span class="ot">&lt;-</span> mpsz3414 <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_area</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will use <em>mutate()</em>&nbsp;of <strong>dplyr</strong> package to compute density. We multiply it by 1000000 to reduce the amount of decimal points by converting it to km2 for easier handling.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-29_02e714a83a2446c8c07a638eeaff825c">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>mpsz3414 <span class="ot">&lt;-</span> mpsz3414 <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span><span class="sc">/</span>Area <span class="sc">*</span> <span class="dv">1000000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can view the density of preschools.</p>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-30_bffc6646af8f40702af3f09ee7f9f2c5">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
Units: [1/m^2]
  [1]  0.00000000  8.93150215  0.00000000  6.71784674  5.16223032  9.70516876
  [7]  7.24989604  6.89216325  5.53101261  1.58316954  3.28434449  6.80952137
 [13]  0.00000000  2.54735962 11.84392175  0.00000000  0.00000000  0.00000000
 [19]  0.00000000  0.40657576  0.00000000  9.68631056  0.00000000  1.48058527
 [25] 10.83710054 15.70722567 35.60169297  5.47445116  6.18629982  8.20434375
 [31]  0.00000000  0.00000000  9.03949026  0.00000000  7.28645544 17.02931505
 [37] 25.35629701 15.89256712  0.00000000 11.15753677  0.00000000  8.55218466
 [43]  3.81906935  0.00000000  3.38235947  0.00000000 14.99604968  1.40732345
 [49]  8.01406205  0.00000000  0.56949216  5.86952041  3.03547315 11.71891220
 [55]  8.14148847  0.00000000  4.50504548  3.56920079  9.33487616  0.00000000
 [61]  5.62143826  0.00000000  3.14611804  9.93599725 17.95935646  0.00000000
 [67]  5.36153142  1.23223830  5.83558926  3.22047037  1.44233198  3.07398190
 [73]  2.21008233  5.73475293  0.00000000  0.00000000  1.82176954  9.49222530
 [79]  0.00000000  0.00000000  2.97422984  0.00000000  8.68525951  1.83998165
 [85]  7.18639790  0.00000000  0.00000000  5.36902632  0.00000000  2.38539919
 [91]  4.15173953  1.17625763  0.00000000  0.00000000  3.71428866  0.00000000
 [97]  0.00000000 10.30968514  0.00000000  3.52586966  6.81950547  0.00000000
[103] 11.20672769  0.00000000  4.07884557  2.10935105  1.51390154  7.67355379
[109] 10.89459084  9.34277714  0.00000000  0.00000000  5.19103594 10.30880422
[115]  0.00000000  4.91199399  8.37774399 13.90186364 13.05635620  4.03408588
[121]  4.68205034  0.00000000  0.00000000  0.00000000 10.30828105  6.59711016
[127]  8.54111363  0.00000000  0.00000000  9.35774736  3.91277524  9.73248928
[133]  9.52960696  4.07004471  9.01512182  0.88420004  5.85700658  9.21924053
[139]  9.38756233  0.00000000  7.29210328 14.33152883  0.95320866  0.00000000
[145]  1.22943315 14.14811689  0.00000000  4.82029416  4.96423679 10.81358754
[151]  3.87478236 16.37550727  4.20286113  1.92511630  0.00000000  2.27575881
[157]  3.78370366  0.00000000  4.54910663  9.37229330 11.20468789  0.00000000
[163] 10.13730087  1.38998948 11.13208882  0.00000000  6.28324782 12.10849477
[169]  1.46373505  5.42827717  2.50973772 11.03366227 10.52072865  9.49878064
[175] 11.24580300 11.12890128 13.93950764  0.00000000  0.00000000 10.35889471
[181]  6.12997351  8.63257212  6.52702292  0.00000000  6.45113675  8.65521161
[187]  2.02537466  0.96587505 13.36459686  4.45419682  0.00000000  3.86526962
[193] 12.69090170  5.93156946  1.62615585  2.07322060  7.12358161  8.11313906
[199]  9.67642203 12.64374315  0.00000000 13.05378261  0.00000000 10.91908952
[205]  4.47169158 10.97443928 15.73682882 10.53521767  0.00000000  7.86180592
[211]  7.94696181  4.61489164  1.02119062  6.11811051 15.06832167 11.36765405
[217]  7.09104861 10.31880873 11.98092893  5.46797281  0.00000000 16.45587097
[223]  6.40125464 14.81499038  4.29058729  6.40314089  2.68546919  8.79682941
[229]  0.47286030  2.09945890 11.21716914  3.17460839  4.01850845  0.00000000
[235]  0.00000000  4.14472875 11.63901574 16.47133302  7.18459670  6.48975999
[241] 10.17545246  4.63093287  9.05523476  1.03085549  2.42737742 11.58770447
[247]  0.78643969 10.46342303 15.77874328  8.60077770  3.25580555  0.00000000
[253] 21.90726711  5.95439968  1.62661251  0.00000000  0.00000000  4.07046653
[259] 11.94152678 16.57069701  0.00000000  5.43686743 13.78099282 15.16440245
[265]  0.00000000  8.46092732 14.10108710  0.00000000  0.05698650  0.00000000
[271]  0.00000000 20.61136242 11.34007216  0.00000000 14.17732715  0.70978094
[277]  4.41176266 34.93133940 11.45820473  0.00000000  0.00000000  7.61420607
[283] 10.20733340 10.18622170  0.01433727  0.00000000 10.54179983  1.67883220
[289]  0.00000000 18.40637075 23.89765810  0.78045947  9.23332461  0.00000000
[295]  0.00000000  7.13352271  0.00000000  0.00000000  0.00000000  7.16914906
[301]  0.00000000  0.00000000  0.13820154  0.00000000 11.25082456 17.08643178
[307]  4.85251417  9.09591416  0.90530070 10.28168016  0.00000000  0.00000000
[313]  0.00000000  0.25535809  0.00000000  0.00000000  1.39575809  0.00000000
[319]  0.00000000  1.22409828  0.00000000  0.00000000  0.00000000</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>7. Exploratory Data Analysis (EDA)</h1>
<hr>
<p>Many geospatial analytics start with Exploratory Data Analysis. We will utilise <em>ggplot2</em> functions to create graphs for EDA purposes.</p>
<section id="investigating-pre-school-density" class="level2">
<h2 class="anchored" data-anchor-id="investigating-pre-school-density">7.1 Investigating Pre School Density</h2>
<p>We can plot a histogram to investigate the distrubtion of <code>PreSch Density</code>.</p>
<section id="histogram-hist-of-mpsz3414presch-density" class="level3">
<h3 class="anchored" data-anchor-id="histogram-hist-of-mpsz3414presch-density">7.1.1 Histogram (hist) of mpsz3414$<code>PreSch Density</code></h3>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-31_adda3d3db22ac6262083ba6dda607d8b">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hoex1_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>hist plots a histogram quickly from the data provided in <code>PreSch Density</code>. However it lacks customisation capabilities. We can customise it further to add appropriate labels using <strong>ggplot2</strong>.</p>
</section>
<section id="histogram-ggplot2-of-mpsz3414presch-density" class="level3">
<h3 class="anchored" data-anchor-id="histogram-ggplot2-of-mpsz3414presch-density">7.1.2 Histogram (ggplot2) of mpsz3414$<code>PreSch Density</code></h3>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-32_04846dc10d915cb2807933e984ea4ab0">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpsz3414,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>))) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"black"</span>,</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Are pre-schools even distributed in Singapore?"</span>,</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"There are many planning sub-zones with a single pre-school on the other hand, </span><span class="sc">\n</span><span class="st"> there are six planning-subzones with at least 20 pre-schools"</span>,</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pre-school density (per km sq)"</span>,</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hoex1_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Scenario:</p>
<p>Using ggplot2, plot a scatterplot showing the relationship between Pre-school Density and Pre-school Count</p>
</div>
</div>
</div>
<div class="cell" data-hash="hoex1_cache/html/unnamed-chunk-33_c17e0a716301195d8304b0d885557d99">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpsz3414,</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>), <span class="at">y =</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>))) <span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"black"</span>,</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">60</span>) <span class="sc">+</span> </span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">60</span>) <span class="sc">+</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Pre-school density (per km sq)"</span>,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Pre-school count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hoex1_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, while the graph works without specifying xlim and ylim, we want to standardise the scales on x and y axes, hence, we specified the limits to be from 0 to 60 on both axes.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Ren Jie’s IS415 Journal</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/renjie-teo">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/renjieteo/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>